### ISSUE TITLE
KeyError when running `eval_yarn_mistral.py` on PassKey

### ISSUE THREAD

**Issue by siqi13579** [OpenBMB/InfiniteBench#1]
执行python3 eval_yarn_mistral.py --task passkey --model_path ../Yarn-Mistral-7b-128k/ 出错

出错信息如下：
src/eval_utils.py", line 204, in create_prompt
    "prompt": eg["prompt"],
KeyError: 'prompt'

如果注释掉这行，mistral的生成结果非常奇怪：
==== Evaluation ====
# examples: 590
Start index: 0
Stop index: 590
Verbose: False
Max tokens: 6
====== Example 0 ======
Truncating...
# tokens before: 125353
# tokens after: 125353
seq_len: 125353
Number of chunks: 980, generating...
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Chunked generation: green.

What is
====== Example 1 ======
Truncating...
# tokens before: 125353
# tokens after: 125353
seq_len: 125353
Number of chunks: 980, generating...
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Chunked generation: green.

What is
====== Example 2 ======
Truncating...
# tokens before: 125353
# tokens after: 125353
seq_len: 125353
Number of chunks: 980, generating...
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Chunked generation: 89415
====== Example 3 ======
Truncating...
# tokens before: 125353
# tokens after: 125353
seq_len: 125353
Number of chunks: 980, generating...
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Chunked generation: green.

What is

**Comment by chen-yingfa** [comment]
This should have been fixed by commit c27d624, please try running the code again.
