### ISSUE TITLE
Why some data in longbook_qa_eng were modified? 

### ISSUE THREAD

**Issue by FranxYao** [OpenBMB/InfiniteBench#12]
Hey great efforts on constructing InfiniBench! One quick question I've noticed:

In a recent upload to HF dataset https://huggingface.co/datasets/xinrongzhang2022/InfiniteBench/commit/f2fd8f04ea3af8304b88de2c58bd33887bcccdb8

You changed 20 questions and answers compared to the original commit in: https://huggingface.co/datasets/xinrongzhang2022/InfiniteBench/commit/bae90aaac350652b7c7292dcf556bdd52542929b

Consequently some numbers based on the previous / current dataset may not be directly comparable. May I ask what are the considerations behind this?

Thanks!

**Comment by tuantuanzhang** [comment]
we correct some typos. Besides, we also update some Q&A to enhance quality, difficulty, and long dependency required by Q.
