### ISSUE TITLE
Generating Math and Code sample

### ISSUE THREAD

**Issue by kai-wen-yang** [OpenBMB/InfiniteBench#15]
Could you please provide the code for generating samples of Math.Find, Math.Calc, Code.RUN and Code.debug?
I want to generate some test sample with shorter length, since my model only support 32k context length.
Thanks a lot!

**Comment by chen-yingfa** [comment]
Hello, we will release the code as soon as possible.

Thank you!

**Comment by tuantuanzhang** [comment]
we have updated the synthetic data code for task Math.Find, Math.Calc and Code.Run. As the examples of the task Code.Debug are annotated by humans, there is no end-to-end generation code.
