### ISSUE TITLE
Inference time of YaRN-Mistral-7B

### ISSUE THREAD

**Issue by ccclyu** [OpenBMB/InfiniteBench#5]
Very useful benchmark!  May I ask how long did it take when you had inference on these tasks using YaRN-Mistral-7B? Did you only use one A100 80GB GPU for inference?

**Comment by chen-yingfa** [comment]
Hello,

We used only one A100 80GB GPU for inference using YaRN-Mistral-7B, and for most tasks, it takes around 10 minutes per example with our implementation `eval_yarn_mistral.py`. So, about 8 hours for Retrieve.KV for instance.

**Comment by WalkerWen** [comment]
一台单卡A100，不会爆显存吗

**Comment by WalkerWen** [comment]
> Hello,
> 
> We used only one A100 80GB GPU for inference using YaRN-Mistral-7B, and for most tasks, it takes around 10 minutes per example with our implementation `eval_yarn_mistral.py`. So, about 8 hours for Retrieve.KV for instance.
一台单卡A100，不会爆显存吗
