### ISSUE TITLE
模型支持长度与测试长度

### ISSUE THREAD

**Issue by iMountTai** [OpenBMB/InfiniteBench#6]
有几个问题，还麻烦您解答，非常感谢：
1. 该bench支持64K甚至32K的长文本测评吗？
2. 如果支持的话，是需要修改`MAX_POSITION_ID `和`TRUNCATE_LEN `中的128为对应模型的支持长度吗，如64k模型修改为`TRUNCATE_LEN =64*1024`？
3. 测试样本中根据长度做了切块，代码逻辑与LongBench是一致的，请问我理解的对吗？

期待您的回复，不胜感激!

**Comment by chen-yingfa** [comment]
你好，

1 和 2： 支持的，`TRUNCATE_LEN` 只是说当输入超出这个长度，就阶段中间部分来强行让输入总是小于 `TRUNCATE_LEN`，而 `MAX_POSITION_ID` 现在应该是没有作用的，我们会在下一个版本删除这个变量。
3：暂时不是很清楚 LongBench 是怎么做的，但是如果你是问关于 `eval_yarn_mistral.py` 中的 `chunk_generate`，那分块纯粹是一种降低显存消耗的技巧，跟普通 generate 是等价的，如果显存足够也可以不这么做的。

**Comment by iMountTai** [comment]
LongBench也是取`input`的头尾部分来切分过长的输入。
请问如果不用`chunk_generate`应该怎么修改代码呢？手里是有一个节点的A40 48G的，感觉目前的生成速度非常慢。qa_zh任务，六张A40，一个样本大约要5分钟，还是64K长度的。

**Comment by chen-yingfa** [comment]
`chunk_generate` 跟普通 `model.generate` 的用法很像，但是因为 Hugging Face 的 attention 实现的原因，你还是会爆内存，可能需要你使用推理框架。另一方面，因为现在 batch size 是 1， 如果你想要通过多卡推理来得到提速，应该需要实现模型并行化，我们的代码也没有这样实现。至于怎么修改代码，其实就是并行化 Hugging Face 的模型，网上应该不少相关内容，这种方法用我们的 `chunk_generate` 应该也可以得到提速。

**Comment by iMountTai** [comment]
谢谢您的回复。所以`chunk_generate `的作用是节省显存？目前并不打算使用模型并行推理，主要是看到代码里设置了`device_map="auto"`，原生支持huggingface多卡推理的，想确认一下如果直接堆卡数推理，不使用`chunk_generate `，是否会速度变快？打扰了，谢谢！

**Comment by chen-yingfa** [comment]
没错，`chunk_generate` 唯一的作用就是降低显存要求（因为 HF 的实现会实例化整个 n * n 的 attention mask，一下子就爆显存了）。如果是通过并行化模型来加速，那么使用 `chunk_generate` 也应该得到加速的。

**Comment by liyucheng09** [comment]
@chen-yingfa 你好，如果test example长于TRUNCATE_LEN的话，是否代表模型无法看到全部的题目信息？

如果这样的话，是否代表有些InfiniteBench中的example无法用来评测32K模型（因为题目太长无法放进去）？

**Comment by chen-yingfa** [comment]
你好，这个问题取决于你打算怎么让模型处理输入，因为API会直接拒绝回答超过特定长度的输入，所以我们总是做截断，但是你也可以将查过模型训练长度的输入喂给模型。

我们认为这不代表InfiniteBench中的题目不能用于评测32K模型，因为实际应用中可能会出现这么长的输入，如果模型因为自身的缺陷而无法看到全部题目信息，因而无法完成任务，那么评测结果就应该体现出这种能力缺陷。
