### ISSUE TITLE
计算测试分数时报错

### ISSUE THREAD

**Issue by iMountTai** [OpenBMB/InfiniteBench#7]
![image](https://github.com/OpenBMB/InfiniteBench/assets/35353688/72c6cbbc-b4ee-4b2c-b0e0-ec26c78ceafb)
math_find的label是个列表，但是要求是`int`或者`float`类型

**Comment by iMountTai** [comment]
对比repo中的preds_passkey.jsonl结果，我的输出如下，请问怎么解决呢？
![image](https://github.com/OpenBMB/InfiniteBench/assets/35353688/1a3bca97-6834-4a42-807d-acbe841086b5)

**Comment by chen-yingfa** [comment]
你好，

对于 math_find 任务，我们的 compute_scores.py 要求 ground_truth 是一个 int 类型。

**Comment by iMountTai** [comment]
但是测试时保存的`ground_truth `是列表

**Comment by chen-yingfa** [comment]
确实，是我们的疏忽，我现在修改一下。

**Comment by chen-yingfa** [comment]
现在应该可以了，感谢您的通知，如果还有问题，请 Reopen issue。
