### ISSUE TITLE
About the data source

### ISSUE THREAD

**Issue by guanzhchen** [OpenBMB/InfiniteBench#8]
Awesome work! Would you have any plans to release the data source? I'm very curious about where the super-long (>100k) code and math data from.

**Comment by chen-yingfa** [comment]
Hello,

The data source will be detailed in our upcoming paper. If you have any concrete questions, I can answer them here. For Code.Debug, the code comes from the repositories of PyPI packages. For Math.Find, Math.Calc, and Code.Run, they are all auto-generated.

**Comment by guanzhchen** [comment]
Thank you! Looking forward to reading your paper.
