### ISSUE TITLE
数据全是手动标注的吗？有没有存在模型生成的部分

### ISSUE THREAD

**Issue by Patrick-Ni** [OpenBMB/InfiniteBench#9]
你好！我想问一下，除了retrieval这种可以通过程序来自动构建的数据集，其他部分全是人工标注的吗？有没有模型辅助生成、人工check的部分？

**Comment by chen-yingfa** [comment]
这个问题跟 #8 重复了，我们数据集有人工标注的也有自动生成的。但是所有数据都经过了人工质量检查。之后我们公布的论文会有详细的介绍。如果你还有其他问题，可以在这里问。
